"""Add description column to product table

Revision ID: 8e2be6d557ff
Revises: 2c77ff3bf42c
Create Date: 2024-01-30 09:17:53.732136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2be6d557ff'
down_revision = '2c77ff3bf42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
